### ISSUE TITLE
Can you please release the basic version?

### ISSUE THREAD

**Issue by foreversun69** [jasonmotylinski/hierarchical-backlinks#1]
Hello sir,

can you please publish the basic version? That would be enough for me to start with, just like the outgoing links.

Kind regards
foreversun

**Comment by hyperphysin** [comment]
yes, please let us install the beta version.

**Comment by jasonmotylinski** [comment]
I have an initial version here: https://github.com/jasonmotylinski/hierarchical-backlinks/releases/tag/untagged-f50403ebb7a1d739618f. It is not at feature parity with the existing backlinks panel but the basics are there (tree hierarchy, text highlighting).
