### ISSUE TITLE
The reverse link BUG is inconsistent with the display of the core plug-in

### ISSUE THREAD

**Issue by jiajiala** [jasonmotylinski/hierarchical-backlinks#19]
![image](https://github.com/user-attachments/assets/bd9f74fe-19c3-411e-82c6-28ae25f1b7c7)
It is correct to display no reverse links in the core plug-inAnd the following hierarchical-backlinks shows a lot of links

**Comment by jasonmotylinski** [comment]
They should be the same. Any chance you can create a sample vault for me to
test with?

**Comment by jiajiala** [comment]
Then there is another point that is different from the core plug-in
The core plugin does not appear to be its own backlink
![image](https://github.com/user-attachments/assets/ccbeed61-3552-4866-9563-de2f643096d1)

**Comment by jasonmotylinski** [comment]
Does this happen in the core Backlink plugin as well? I'm using the same data cache as the core plugin.

**Comment by jasonmotylinski** [comment]
I've only been able to reproduce the last bug wherein backlinks list contains a reference to the current file when the current file references itself. The fix will be included in 1.0.5
